export const BUSINESS = {
  name: "Abogadas Talca",
  tagline: "+12 años resolviendo casos en la Región del Maule.",
  description:
    "Estudio jurídico en Talca. Derecho de familia, laboral, civil y penal.",
  phone: "+56 9 6224 2528",
  whatsapp: "56962242528",
  email: "abogadastalca.cl@gmail.com",
  address: "1 Poniente 1258, Of. 1111, Talca",
  instagram: "https://www.instagram.com/abogadastalca/",
  web: "https://abogadastalca.cl",
  googleMapsEmbed: "",
  hours: "Lunes a Viernes, 9:00 - 18:00 hrs",
  waMessage: "Hola! Necesito ayuda en [COLOCA TEMA]",
} as const;

export const TEAM = [
  {
    name: "Catalina del Carmen Fuentes Tapia",
    title: "Abogada",
    subtitle: "Derecho de Familia y Laboral",
    bio: "Licenciada en Ciencias Jurídicas y Sociales. +12 años de ejercicio en la Región del Maule. Especializada en litigación de familia y defensa de trabajadores.",
    photo: "/images/abogadas/presentacion-abogada.jpg",
    linkedin: "",
  },
] as const;

export const AREAS = [
  {
    slug: "derecho-familia",
    title: "Derecho de Familia",
    short: "Cuidado personal, pensión de alimentos, régimen comunicacional, divorcios y más.",
    description: "Gestionamos procesos de familia con rigor legal y trato directo. Te informamos los tiempos y las opciones reales antes de comenzar.",
    seoTitle: "Abogado de Familia Talca — Divorcio, Pensión de Alimentos y Tuición",
    metaDescription: "Abogadas de familia en Talca. Divorcios, pensión de alimentos, tuición, custodia y medidas de protección VIF. Atención en todo el Maule. Consulta gratuita.",
    keywords: [
      "abogado familia talca",
      "divorcio talca",
      "pension alimentos talca",
      "tuicion talca",
      "violencia intrafamiliar maule",
      "custodia hijos talca",
      "regimen visitas talca",
    ],
    longDescription: [
      "Los conflictos familiares son los más difíciles de enfrentar porque involucran a las personas que más importan. En Abogadas Talca acompañamos a nuestras clientes en cada etapa del proceso con información clara, plazos reales y un enfoque orientado al bienestar de sus hijos.",
      "El Juzgado de Familia de Talca tramita divorcios, pensiones de alimentos, tuición, régimen de visitas y medidas de protección por violencia intrafamiliar. Cada caso tiene sus particularidades: un divorcio de mutuo acuerdo tarda entre 3 y 6 meses; uno unilateral puede extenderse más. La pensión de alimentos puede solicitarse de forma provisional desde el primer día de la demanda.",
      "Si estás enfrentando una situación de violencia intrafamiliar, actuamos de inmediato para obtener medidas de protección. No tienes que esperar.",
    ],
    proceso: [
      { step: "Consulta gratuita", desc: "Escuchamos tu situación, te explicamos qué tipo de proceso corresponde y cuáles son los tiempos y costos reales." },
      { step: "Preparación del caso", desc: "Reunimos la documentación necesaria, redactamos la demanda o solicitud y te explicamos cada paso antes de presentarla." },
      { step: "Audiencias y negociación", desc: "Te acompañamos en todas las audiencias del Juzgado de Familia. Negociamos acuerdos cuando benefician a tu familia, litigamos cuando es necesario." },
      { step: "Resolución y cumplimiento", desc: "Una vez dictada la sentencia o aprobado el acuerdo, te ayudamos a hacer efectivo el cumplimiento si la otra parte no lo respeta." },
    ],
    faq: [
      { q: "¿Cuánto tarda un divorcio en Chile?", a: "El divorcio de mutuo acuerdo tarda entre 3 y 6 meses desde la presentación. El divorcio unilateral por cese de convivencia requiere al menos 3 años de separación y puede tardar más según la carga del tribunal." },
      { q: "¿Cómo se calcula la pensión de alimentos?", a: "El tribunal considera los ingresos del alimentante y las necesidades del hijo. La ley establece un mínimo del 40% del ingreso mínimo mensual por hijo. Puede pedirse una pensión provisoria desde el primer día de la demanda." },
      { q: "¿Qué hago si mi pareja no quiere divorciarse?", a: "Puedes demandar divorcio unilateral si llevan al menos 3 años separados con cese de convivencia acreditado. No necesitas el consentimiento de la otra parte." },
      { q: "¿Puedo pedir medidas de protección por violencia intrafamiliar?", a: "Sí. Puedes denunciar en Carabineros, PDI o directamente en el Juzgado de Familia. El tribunal puede dictar medidas cautelares el mismo día, incluyendo la prohibición de acercamiento." },
    ],
    casos: [
      "Divorcio unilateral o de mutuo acuerdo",
      "Pensión de alimentos",
      "Tuición y custodia",
      "Régimen de visitas",
      "Violencia intrafamiliar — medidas de protección",
      "Adopción",
    ],
  },
  {
    slug: "derecho-civil",
    title: "Derecho Civil",
    short: "Contratos, obligaciones y responsabilidad civil. Te asesoramos en cada etapa.",
    description: "Redactamos contratos, tramitamos herencias y defendemos tus derechos en disputas civiles. Claridad y precisión en cada gestión.",
    seoTitle: "Abogado Civil Talca — Herencias, Posesión Efectiva y Contratos",
    metaDescription: "Abogadas civiles en Talca. Posesión efectiva, herencias, contratos y arrendamientos. +12 años en la Región del Maule. Presupuesto sin letra chica. Consulta gratis.",
    keywords: [
      "abogado civil talca",
      "posesion efectiva talca",
      "herencia maule",
      "contratos talca",
      "arrendamiento talca",
      "responsabilidad civil maule",
      "deudas obligaciones talca",
    ],
    longDescription: [
      "El derecho civil regula la mayoría de las relaciones jurídicas cotidianas: los contratos que firmamos, las deudas que contraemos, los bienes que heredamos. En Abogadas Talca tramitamos posesiones efectivas, redactamos y revisamos contratos, y representamos a nuestras clientes en disputas civiles ante los tribunales de la Región del Maule.",
      "La posesión efectiva es el trámite legal para que los herederos puedan disponer de los bienes de una persona fallecida. Puede tramitarse en el Registro Civil (herencias intestadas sin bienes raíces) o ante el tribunal civil (cuando hay bienes raíces o testamento). El proceso tiene plazos y requisitos específicos que conviene conocer antes de iniciar.",
      "En contratos y arrendamientos, un documento bien redactado evita conflictos futuros. Revisamos contratos antes de firmar y actuamos cuando la otra parte no cumple sus obligaciones.",
    ],
    proceso: [
      { step: "Consulta gratuita", desc: "Revisamos tu situación: tipo de bienes, número de herederos, existencia de testamento, deudas del causante." },
      { step: "Tramitación", desc: "Preparamos todos los documentos y presentamos la solicitud en el Registro Civil o el tribunal correspondiente según el caso." },
      { step: "Publicaciones e inscripciones", desc: "Gestionamos las publicaciones legales requeridas y la inscripción en el Conservador de Bienes Raíces cuando corresponde." },
      { step: "Cierre", desc: "Una vez obtenida la posesión efectiva o resuelta la disputa, te entregamos todos los documentos y te explicamos los pasos siguientes." },
    ],
    faq: [
      { q: "¿Qué es la posesión efectiva y cuándo se necesita?", a: "Es la resolución legal que reconoce a los herederos como continuadores del patrimonio del fallecido. Se necesita para transferir bienes raíces, cuentas bancarias y vehículos a nombre de los herederos." },
      { q: "¿Cuánto tarda la posesión efectiva?", a: "La tramitación ante el Registro Civil (sin bienes raíces) puede tardar entre 1 y 3 meses. Ante el tribunal civil, el proceso es más largo y depende de la carga del tribunal." },
      { q: "¿Qué pasa si el arrendatario no paga?", a: "Puedes iniciar un juicio de arrendamiento ante el tribunal civil. Si el contrato está bien redactado, el proceso puede resolverse en pocos meses con el lanzamiento del arrendatario y el cobro de las rentas impagas." },
      { q: "¿Es necesario un abogado para revisar un contrato?", a: "No es obligatorio, pero es altamente recomendable. Muchos conflictos civiles surgen de contratos mal redactados que no contemplan cláusulas básicas de protección. Una revisión previa evita problemas mayores." },
    ],
    casos: [
      "Redacción y revisión de contratos",
      "Arrendamientos y cobranzas",
      "Herencias y posesión efectiva",
      "Responsabilidad civil",
      "Deudas y obligaciones",
    ],
  },
  {
    slug: "derecho-laboral",
    title: "Derecho Laboral",
    short: "Despidos injustificados, acoso laboral, liquidaciones y tutela de derechos.",
    description: "Representamos trabajadores ante la Inspección del Trabajo y los Tribunales Laborales. Actuamos con rapidez porque los plazos importan.",
    seoTitle: "Abogado Laboral Talca — Despido Injustificado, Acoso y Liquidaciones",
    metaDescription: "Abogadas laboralistas en Talca. Representamos trabajadores en despidos injustificados, acoso laboral y tutela de derechos. +12 años en el Maule. Consulta gratis.",
    keywords: [
      "abogado laboral talca",
      "despido injustificado talca",
      "acoso laboral maule",
      "tutela derechos fundamentales talca",
      "liquidacion incorrecta talca",
      "abogado trabajo talca",
      "negociacion colectiva maule",
    ],
    longDescription: [
      "Si fuiste despedido sin justificación, no recibiste tu liquidación correcta o sufres acoso en el trabajo, tienes derechos que la ley protege — y plazos que no puedes perder. En Abogadas Talca representamos trabajadores ante la Inspección del Trabajo y los Tribunales Laborales de la Región del Maule, con más de 12 años de experiencia en litigación laboral.",
      "El Código del Trabajo chileno establece causales específicas de despido. Si el empleador no las cumple o no paga las indemnizaciones correspondientes, tienes derecho a demandar. Lo mismo aplica para el acoso laboral: la Ley 20.607 lo tipifica y la tutela de derechos fundamentales permite actuar con rapidez ante el tribunal.",
      "Actuamos con urgencia porque en derecho laboral los plazos son breves — generalmente 60 días hábiles desde el despido para presentar la demanda. No dejes pasar el tiempo: una consulta gratuita con nosotras puede cambiar el resultado de tu caso.",
    ],
    proceso: [
      { step: "Consulta gratuita", desc: "Evaluamos tu situación laboral, revisamos documentos (contrato, liquidación, finiquito) y te explicamos tus derechos reales." },
      { step: "Estrategia legal", desc: "Decidimos si presentar una denuncia a la Inspección del Trabajo, una demanda laboral o una acción de tutela, según la urgencia y el caso." },
      { step: "Presentación y audiencias", desc: "Preparamos la demanda, la presentamos en el Juzgado de Letras del Trabajo y te acompañamos en cada audiencia." },
      { step: "Resultado y cobro", desc: "Negociamos acuerdos o litigamos hasta sentencia. Si hay condena, gestionamos el cobro de las indemnizaciones." },
    ],
    faq: [
      { q: "¿Cuánto tiempo tengo para demandar un despido injustificado?", a: "60 días hábiles desde la fecha de despido. Pasado ese plazo, la acción prescribe. Es fundamental actuar rápido." },
      { q: "¿Qué es la tutela de derechos fundamentales?", a: "Es una acción judicial que protege derechos como la dignidad, la privacidad y la no discriminación en el trabajo. Tiene plazos acotados y el tribunal actúa con mayor rapidez." },
      { q: "¿Puedo demandar si firmé el finiquito?", a: "Depende. Si firmaste bajo presión o sin leer, o si el finiquito no incluye todas las indemnizaciones que te corresponden, es posible impugnarlo. Consulta antes de firmar cualquier documento." },
      { q: "¿Cuánto me corresponde por despido injustificado?", a: "Como mínimo, 30 días de remuneración por año de servicio, más el feriado proporcional y otros beneficios. El monto exacto depende de tu antigüedad, sueldo y tipo de contrato." },
    ],
    casos: [
      "Despido injustificado",
      "Acoso laboral o sexual",
      "Liquidaciones incorrectas",
      "Tutela de derechos fundamentales",
      "Negociación colectiva",
    ],
  },
  {
    slug: "derecho-inmobiliario",
    title: "Derecho Inmobiliario",
    short: "Escrituras, contratos de compraventa, loteos y subdivisiones de terrenos.",
    description: "Te asesoramos en la compra, venta, arriendo y subdivisión de bienes raíces. Revisamos cada contrato para proteger tu inversión.",
    seoTitle: "Abogado Inmobiliario Talca — Compraventa, Escrituras y Loteos",
    metaDescription: "Abogadas inmobiliarias en Talca. Escrituras de compraventa, contratos de arriendo, loteos y subdivisiones. Asesoría legal en toda la Región del Maule. Consulta gratis.",
    keywords: [
      "abogado inmobiliario talca",
      "escritura compraventa talca",
      "loteo subdivision maule",
      "contrato arriendo talca",
      "bienes raices abogado talca",
      "promesa compraventa maule",
    ],
    longDescription: [
      "Las operaciones inmobiliarias involucran montos significativos y documentos complejos. Un error en un contrato de compraventa o en una promesa puede costar caro. En Abogadas Talca revisamos cada documento antes de que lo firmes y te explicamos exactamente qué estás comprometiendo.",
      "Tramitamos escrituras de compraventa, contratos de arriendo, promesas de compraventa, loteos y subdivisiones de terrenos ante el Conservador de Bienes Raíces y los organismos competentes de la Región del Maule.",
      "Si ya firmaste un contrato y la otra parte no cumple, actuamos judicialmente para proteger tus derechos e inversión.",
    ],
    proceso: [
      { step: "Revisión del contrato", desc: "Analizamos el título, las condiciones del inmueble y el historial registral antes de cualquier operación." },
      { step: "Redacción o corrección", desc: "Redactamos o corregimos el contrato incorporando cláusulas de protección claras y sin ambigüedades." },
      { step: "Trámites notariales y registrales", desc: "Coordinamos la firma ante notario y la inscripción en el Conservador de Bienes Raíces." },
      { step: "Seguimiento hasta el cierre", desc: "Acompañamos la operación hasta que la transferencia quede inscrita y legalmente perfeccionada." },
    ],
    faq: [
      { q: "¿Es obligatorio un abogado en una compraventa?", a: "No es obligatorio, pero es altamente recomendable. El notario da fe del acto, pero no vela por tus intereses. Un abogado revisa el título, las deudas del inmueble y las condiciones del contrato antes de firmar." },
      { q: "¿Qué es una promesa de compraventa?", a: "Es un contrato en que las partes se obligan a celebrar en el futuro la compraventa definitiva. Debe cumplir requisitos formales específicos para ser válida y ejecutable." },
      { q: "¿Qué revisa el abogado antes de comprar una propiedad?", a: "Revisamos el certificado de dominio vigente, las hipotecas y gravámenes, los embargos, la situación tributaria y las condiciones urbanísticas del inmueble." },
      { q: "¿Qué pasa si el vendedor no transfiere la propiedad después de la promesa?", a: "Si el vendedor incumple, puedes demandar el cumplimiento forzado del contrato o pedir la resolución con indemnización de perjuicios. El monto de la multa pactada en la promesa también es exigible." },
    ],
    casos: [
      "Compraventa de inmuebles",
      "Promesas de compraventa",
      "Contratos de arriendo",
      "Loteos y subdivisiones",
      "Inscripciones en el Conservador de Bienes Raíces",
      "Incumplimiento de contratos inmobiliarios",
    ],
  },
  {
    slug: "derecho-penal",
    title: "Derecho Penal",
    short: "Defensa penal, representación de víctimas y recursos de amparo.",
    description: "Actuamos desde la primera audiencia. Defensa de imputados y representación de víctimas con estrategia y firmeza.",
    seoTitle: "Abogado Penal Talca — Defensa Penal y Representación de Víctimas",
    metaDescription: "Abogadas penalistas en Talca. Defensa de imputados, querellas, representación de víctimas y recursos de amparo. Actuamos desde la primera audiencia en el Maule.",
    keywords: [
      "abogado penal talca",
      "defensa penal maule",
      "querella talca",
      "recurso amparo maule",
      "representacion victimas talca",
      "abogado criminal talca",
      "defensa imputado maule",
    ],
    longDescription: [
      "En derecho penal, cada hora cuenta. Si eres imputado o víctima de un delito en la Región del Maule, actuar con rapidez y contar con representación legal especializada puede determinar el resultado del proceso. En Abogadas Talca actuamos desde la primera audiencia — imputación, formalización o medidas cautelares — con estrategia y firmeza.",
      "Representamos tanto a imputados como a víctimas. Para los imputados, diseñamos una defensa técnica orientada a la mejor salida procesal posible: acuerdo reparatorio, suspensión condicional, sentencia favorable o reducción de pena. Para las víctimas, presentamos querellas y participamos activamente en el proceso para asegurar que sus derechos sean reconocidos.",
      "También tramitamos recursos de amparo cuando existe una privación ilegal o arbitraria de libertad. Este recurso tiene carácter urgente y lo presentamos ante la Corte de Apelaciones de forma inmediata.",
    ],
    proceso: [
      { step: "Consulta urgente", desc: "Evaluamos el caso de inmediato. Si hay detención o formalización inminente, coordinamos la representación en la primera audiencia." },
      { step: "Defensa o querella", desc: "Para imputados: preparamos la defensa técnica. Para víctimas: redactamos y presentamos la querella ante el tribunal competente." },
      { step: "Audiencias", desc: "Te acompañamos en todas las audiencias del proceso penal: formalización, cautelares, preparación de juicio oral y juicio." },
      { step: "Resultado", desc: "Negociamos salidas alternativas cuando benefician a nuestro cliente, o litigamos hasta el juicio oral. Incluimos apelación si la sentencia es desfavorable." },
    ],
    faq: [
      { q: "¿Qué hago si me citaron a declarar a la PDI o Fiscalía?", a: "No estás obligado a declarar sin un abogado presente. Consulta con nosotras antes de concurrir. Tienes derecho a asesoría legal en todo momento del proceso penal." },
      { q: "¿Qué es la formalización de cargos?", a: "Es la audiencia en que el Ministerio Público comunica al imputado los cargos que investiga. A partir de ese momento el proceso tiene plazos formales y el imputado tiene derechos procesales específicos." },
      { q: "¿Cuándo puedo presentar una querella?", a: "La víctima puede presentar querella en cualquier momento de la investigación, antes del cierre. La querella te otorga la calidad de parte en el proceso y te permite controlar el avance de la causa." },
      { q: "¿Qué es un recurso de amparo?", a: "Es una acción constitucional urgente para proteger la libertad personal cuando hay una detención o privación de libertad ilegal o arbitraria. La Corte de Apelaciones debe resolverlo con urgencia, generalmente en 24 horas." },
    ],
    casos: [
      "Defensa penal — imputados",
      "Querella y representación de víctimas",
      "Recursos de amparo",
      "Delitos informáticos",
      "Violencia intrafamiliar — denuncia penal",
    ],
  },
  {
    slug: "defensa-deudores",
    title: "Defensa de Deudores",
    short: "CAE, cobranza judicial y declaración de quiebra por insolvencia. Conoce tus derechos.",
    description: "La Tesorería no siempre tiene jurisdicción para cobrarte. Analizamos tu caso y oponemos excepciones antes de que venza el plazo.",
    seoTitle: "Defensa de Deudores Talca — CAE, Cobranza Judicial e Insolvencia",
    metaDescription: "Abogadas especializadas en defensa de deudores en Talca. CAE, cobranza judicial, prescripción y quiebra por insolvencia. Primera consulta gratuita. Región del Maule.",
    keywords: [
      "defensa deudores talca",
      "abogado cae talca",
      "cobranza judicial maule",
      "prescripcion deuda talca",
      "quiebra insolvencia maule",
      "tesoreria cae defensa",
      "abogado deudas talca",
    ],
    longDescription: [
      "¿Recibiste una notificación de la Tesorería por un CAE? ¿Enfrentas un juicio de cobranza o una amenaza de quiebra? Antes de asumir que debes pagar, es fundamental analizar la legalidad del cobro. La Tesorería no siempre tiene jurisdicción para ejecutar este tipo de deudas.",
      "El Art. 18 bis de la Ley 20.027 establece que el cobro del CAE corresponde al juez civil, no al procedimiento tributario. Si la Tesorería usa el cauce tributario, existen argumentos sólidos para frenar el proceso. Tienes hasta 30 días hábiles desde la notificación para iniciar tu defensa.",
      "También analizamos juicios de cobranza ejecutiva de bancos y otros acreedores, revisando prescripción, vicios del título y excepciones disponibles. En casos de insolvencia, evaluamos mecanismos de renegociación antes de que un proceso de quiebra te afecte.",
    ],
    proceso: [
      { step: "Consulta urgente", desc: "Revisamos la notificación recibida e identificamos el tipo de cobro, el plazo disponible y las excepciones aplicables." },
      { step: "Oposición de excepciones", desc: "Redactamos y presentamos el escrito de excepciones ante el tribunal competente dentro del plazo legal." },
      { step: "Defensa en audiencias", desc: "Te representamos en todas las audiencias del proceso de cobranza, argumentando con base en la ley y la jurisprudencia." },
      { step: "Resolución del caso", desc: "Buscamos la mejor salida: nulidad del cobro, prescripción, acuerdo extrajudicial o defensa completa hasta sentencia." },
    ],
    faq: [
      { q: "¿Puede la Tesorería cobrarme el CAE como si fuera un impuesto?", a: "No necesariamente. El Art. 18 bis de la Ley 20.027 establece que el cobro del CAE se tramita ante el juez civil, no mediante el procedimiento tributario. Si la Tesorería usa el cauce tributario, existen argumentos sólidos para oponerse." },
      { q: "¿Cuánto tiempo tengo para iniciar mi defensa?", a: "Generalmente 30 días hábiles desde la notificación del mandamiento de ejecución. Es fundamental no dejar vencer este plazo." },
      { q: "¿Qué es la prescripción de la deuda?", a: "Si han transcurrido más de 3 años desde que la deuda era exigible sin acto interruptivo acreditado, la acción puede estar prescrita. Si el Fisco invoca el régimen tributario, también le aplica la prescripción tributaria de ese mismo régimen." },
      { q: "¿Qué pasa si no puedo pagar mis deudas?", a: "Existen mecanismos legales de renegociación antes de llegar a la quiebra. Analizamos tu situación patrimonial y te orientamos sobre las opciones disponibles en la ley chilena." },
    ],
    casos: [
      "Defensa ante cobro de CAE por Tesorería",
      "Oposición de excepciones en juicio ejecutivo",
      "Prescripción de deudas",
      "Juicios de cobranza bancaria",
      "Renegociación de deudas",
      "Declaración de quiebra e insolvencia",
    ],
  },
] as const;

export const TESTIMONIALS = [
  {
    quote: "Me ayudaron con el divorcio en poco tiempo. Me explicaron todo con claridad y se cumplieron los plazos que me dieron.",
    name: "María J.",
    case: "Divorcio · Talca",
    rating: 5,
  },
  {
    quote: "Logré que me pagaran lo que me debían después de un despido injusto. Sin ellas no sabría cómo reclamar.",
    name: "Carolina R.",
    case: "Despido injustificado · Curicó",
    rating: 5,
  },
  {
    quote: "Tramitaron la posesión efectiva de mi madre rápido y sin complicaciones. Muy profesionales.",
    name: "Claudia M.",
    case: "Herencia · Linares",
    rating: 5,
  },
] as const;

export const FAQ = [
  {
    q: "¿La primera consulta tiene costo?",
    a: "No. La primera consulta es gratuita, por WhatsApp o en nuestras oficinas en Talca.",
  },
  {
    q: "¿Atienden en toda la Región del Maule?",
    a: "Sí. Atendemos clientes de Talca, Curicó, Linares, Constitución y toda la región. Muchas consultas se realizan de forma remota.",
  },
  {
    q: "¿Cuánto tarda un divorcio?",
    a: "Un divorcio de mutuo acuerdo puede resolverse entre 3 y 6 meses. El unilateral depende del caso. Te informamos los tiempos reales antes de comenzar.",
  },
  {
    q: "¿Cómo me contacto en caso de urgencia?",
    a: "Por WhatsApp. Respondemos el mismo día en horario hábil. Para casos de violencia intrafamiliar, actuamos de inmediato.",
  },
  {
    q: "¿Cuánto cobran?",
    a: "Los honorarios dependen del tipo y complejidad del caso. Antes de comenzar recibes un presupuesto claro y sin letra chica.",
  },
  {
    q: "¿Actúan en juicio?",
    a: "Sí. Somos abogadas patrocinantes en todas las instancias del proceso, desde la primera audiencia hasta el cierre del caso.",
  },
] as const;
